In [7]:
#######   EXERCICE 1

#Déclaration de la liste
exo1_liste = []

#Utilisation d'une variable x prenant les valeurs 2000 jusqu'à 3200 par pas de 1, avec une boucle for
for x in range(2000,3201):
    
    #On vérifie si la valeur de x est divisible par 7 (leur modulo serait 0) et non multiple de 5 (leur modulo serait différent de 0), avec une clause if
    if x%7==0 and x%5!=0:
        
        #Si la valeur de x répond à ces deux confitions, on l'ajoute à la liste
        exo1_liste.append(x)
        
#Affichage de la liste à la sortie de la boucle for
print(exo1_liste)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [8]:
#######   EXERCICE 2

def factoriel():
    #Utilisation d'une boucle while pour répéter le programme 
    while True:

        #Utilisation d'un bloc try ... except pour s'assurer que l'utilisateur entre un nombre entier, et éviter l'affichage d'une exception
        try:

            #Création des variables, x étant le nombre entre par l'utilisateur, et fact le résultat du factoriel
            x = int(input("Veuillez entrer un nombre entier: "))
            fact = 1

            #Utilisation d'une clause if pour vérifier que le nombre entre par l'utilisateur est positif ou nul
            if x>=0:

                #Si la condition est vérifiée, on utilise une boucle for avec une vaiable y prenant les valeurs de 1 à la valeur donnée
                for y in range(1,x+1):

                    #Pour chaque valeur de y on le multiplie à la valeur de la variable fact pour avoir au final le factoriel du nombre entré
                    fact *= y

                #A la sortie de la boucle for on affiche le résultat du factoriel et on sort de la boucle while
                print(fact)
                break

            #Si le nombre entre est négatif, on affiche le message suivant et la boucle while reprend
            else:
                print("Veuillez entrer un nombre positif ou null")

        #On capte l'exception renvoyée par le système au cas ou l'entrée utilisateur est vide ou différente d'un nombre, pour renvoyer le message suivant, et la boucle while reprend
        except ValueError:
            print("Ce n'est pas un nombre entier. Veuillez réessayer.")
            
factoriel()

Veuillez entrer un nombre entier: 
Ce n'est pas un nombre entier. Veuillez réessayer.
Veuillez entrer un nombre entier: jk
Ce n'est pas un nombre entier. Veuillez réessayer.
Veuillez entrer un nombre entier: -8
Veuillez entrer un nombre positif ou null
Veuillez entrer un nombre entier: 5
120


In [9]:
#######   EXERCICE 3

#Utilisation d'une boucle while pour répéter le programme 
while True:
    
    #Utilisation d'un bloc try ... except pour s'assurer que l'utilisateur entre un nombre entier, et éviter l'affichage d'une exception
    try:
        
        #Création des variables avec n prenant un entier saisi par l'utilisateur, et exo2_dict étant le dictionnaire
        n = int(input("Veuillez entrer un nombre entier positif non nul : "))
        exo2_dict = {}

        #Utilisation d'une clause if pour vérifie que n soit positif et différent de 0
        if n>=1:

            #Utilisation d'une boucle for avec une variable x allant de 1 a n inclu
            for x in range(1,n+1):
                
                #Pour chaque valeur de x, on calcule son carré et l'insère dans le dictionnaire
                exo2_dict[x]=x**2
                
            #Affichage du dictionnaire à la sortie de la boucle for, et arret de la boucle while
            print(exo2_dict)
            break
            
        #Si la condition n'est pas verifiée, on affiche le message suivant et la boucle while reprend
        else:
            print("Veuillez entrer un nombre positif non null")
            
    #On capte l'exception renvoyée par le systeme au cas ou l'entrée utilisateur est vide ou différente d'un nombre, pour renvoyer le message suivant, et la boucle while reprend
    except ValueError:
        print("Ce n'est pas un nombre entier. Veuillez réessayer.")

Veuillez entrer un nombre entier positif non nul : 
Ce n'est pas un nombre entier. Veuillez réessayer.
Veuillez entrer un nombre entier positif non nul : hu
Ce n'est pas un nombre entier. Veuillez réessayer.
Veuillez entrer un nombre entier positif non nul : 0
Veuillez entrer un nombre positif non null
Veuillez entrer un nombre entier positif non nul : -5
Veuillez entrer un nombre positif non null
Veuillez entrer un nombre entier positif non nul : 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [10]:
#######   EXERCICE 4

#Déclaration de la variable devant contenir la chaine originelle
first_string=""

#Déclaration d'une boucle while pour s'assurer que l'utilisateur entre bien une chaine de caractères
while first_string=="":
    first_string = input("Veuillez entrer une chaine de caracteres : ")

#Déclaration d'une boucle while pour s'assurer que l'utilisateur entre un entier comme index
while True:
    try:
        
        #Déclaration de la variable n contenant l'entrée utilisateur et étant l'index du caractere à supprimer
        n = int(input(f"Veuillez entrer un index a effacer, entre 0 et {len(first_string)-1} :"))
        
        #Utilisation d'une clause if pour vérifier si l'index entré est negatif ou superieur à celui maximum de la chaine de caracteres
        if n < 0 or n >= len(first_string):

            #Si la condition est vérifiée, on affiche le message suivant et la boucle while recommence
            print("Index hors de portée. Veuillez réessayer.")
            continue

        #Déclaration de la variable devant contenir la chaine de carateres après suppression du caractère indiqué
        second_string = ""

        #Utilisation d'une boucle for avec une variable x parcourant les index de la chaine de caractères initiale
        for x in range(0,len(first_string)):

            #Utilisation d'une clause if pour vérifier, à chaque iteration, que la valeur de x soit différente de celle de n
            if x!=n:
                
                #Si la condition est vérifiée, le caractere à l'index x est rajouté à la chaine de caractères finale
                second_string+=first_string[x]

        #A la sortie de la boucle for, on affiche la chaine de caractère finale, et sort de la boucle while
        print("La chaine", first_string, ", sans le caractere a lindex", n, " donne: ", second_string)
        break

    #Au cas ou l'utilisateur entre un caracte autre qu'un chiffre ou n'entre rien, le message suivant est affiché, et la boucle while reprend
    except ValueError:
        print("Format non pris en charge. Veuillez réessayer.")

Veuillez entrer une chaine de caracteres : 
Veuillez entrer une chaine de caracteres : thioro
Veuillez entrer un index a effacer, entre 0 et 5 :-6
Index hors de portée. Veuillez réessayer.
Veuillez entrer un index a effacer, entre 0 et 5 :9
Index hors de portée. Veuillez réessayer.
Veuillez entrer un index a effacer, entre 0 et 5 :4
La chaine thioro , sans le caractere a lindex 4  donne:  thioo


In [11]:
#######   EXERCICE 5


#Importation du package numpy pour utiliser des matrices numpy et leurs méthodes. On designe np comme alias pour ne pas répéter numpy
import numpy as np

#creation d'une fonction prenant comme parametre un tuple et cree une matrice
def user_arr5(tuple):
    
    #declaration d'une liste qui va contenir toutes les lignes de la matrice à créer
    data = []
    print("Creation d'une matrice")
    
    #Utilisation de deux boucles for imbriquées. 
    #La premiere boucle for parcoure le nombre de lignes à créer pour la matrice
    for x in range(tuple[0]):
        
        #Déclaration d'une liste qui va contenir les éléments d'une ligne
        row = []
        print(f"\n Ligne {x+1} :")
        
        #La deuxième boucle for parcoure les colonnes d'une ligne et demande à l'utilisateur d'entrer une valeur pour chaque élément
        for y in range(tuple[1]):
            val = int(input(f"Entrez la valeur pour la colonne {y+1}: "))
            row.append(val)
            
        #La ligne obtenue est ajoutée à la liste de toutes les lignes
        data.append(row)
        
    #A la sortie de toutes les boucles for, la liste est convertie en array et la fonction retourne la matrice
    arr = np.array(data)
    return arr

#Utilisation d'une boucle while pour recommencer le programme en cas d'erreur
while True:
    
    #Utilisation d'un bloc try ... except pour s'assurer que l'entree utilisateur ne soit pas vide ou differente de chiffres
    try:
        
        #Création d'un tuple de deux éléments à entrer par l'utilisateur, contenant les valeurs du schéma de la matrice originelle
        urtuple = (int(input("entrez nombre de colonnes : ")),int(input("nbre de lignes : ")))
        
        #Utilisation d'une clause if pour vérifier si les valeurs du tuple sont négatives ou nulles
        if urtuple[0]<=0 or urtuple[1]<=0:
            
            #Si les conditions sont vérifiées, le message suivant est affiché et la boucle while reprend
            print("Veuillez entrer des valeurs positives et non nulles")
            continue
            
        #Création d'une matrice numpy d'origine en utilisant la fonction définie plus haut
        origin_array = user_arr5(urtuple)

        #Création d'une liste en utilisant la méthode tolist() du package numpy pour convertir la matrice en une liste
        test_list = origin_array.tolist()

        #Affichage de la matrice d'origine et de la liste résultante avec des sauts de ligne. La boucle while est ensuite arretée
        print("Original array elements: \n", origin_array, "\nArray to list: ", test_list)
        break
    
    #Au cas ou lùutilisateur n'entre pas de chiffres, le systèmes renverrai une exception. Elle est captée et le message suivant est affiché à la place
    except ValueError:
        print("Veuillez entrer des chiffres")

entrez nombre de colonnes : 2
nbre de lignes : 2
Creation d'une matrice

 Ligne 1 :
Entrez la valeur pour la colonne 1: 1
Entrez la valeur pour la colonne 2: 3

 Ligne 2 :
Entrez la valeur pour la colonne 1: 8
Entrez la valeur pour la colonne 2: 6
Original array elements: 
 [[1 3]
 [8 6]] 
Array to list:  [[1, 3], [8, 6]]


In [12]:
#######   EXERCICE 6

#Importation du package numpy pour utiliser des matrices numpy et leurs méthodes. On designe np comme alias pour ne pas répéter numpy
import numpy as np


#creation d'une fonction prenant comme parametre un tuple et cree une matrice
def user_arr6(tuple):
    
    #declaration d'une liste qui va contenir toutes les lignes de la matrice à créer
    data = []
    print("Creation d'une matrice")
    
    #Utilisation de deux boucles for imbriquées. 
    #La premiere boucle for parcoure le nombre de lignes à créer pour la matrice
    for x in range(tuple[0]):
        
        #Déclaration d'une liste qui va contenir les éléments d'une ligne
        row = []
        print(f"\n Ligne {x+1} :")
        
        #La deuxième boucle for parcoure les colonnes d'une ligne et demande à l'utilisateur d'entrer une valeur pour chaque élément
        for y in range(tuple[1]):
            val = int(input(f"Entrez la valeur pour la colonne {y+1} : "))
            row.append(val)
            
        #La ligne obtenue est ajoutée à la liste de toutes les lignes
        data.append(row)
        
    #A la sortie de toutes les boucles for, la liste est convertie en array et la fonction retourne la matrice
    arr = np.array(data)
    return arr

#Utilisation d'une boucle while pour recommencer le programme en cas d'erreur
while True:
    
    #Utilisation d'un bloc try ... except pour s'assurer que l'entree utilisateur ne soit pas vide ou differente de chiffres
    try:
        
        #Création d'un tuple de deux éléments à entrer par l'utilisateur, contenant les valeurs du schéma de la matrice originelle
        urtuple = (int(input("entrez nombre de colonnes : ")),int(input("nbre de lignes : ")))
        
        #Utilisation d'une clause if pour vérifier si les valeurs du tuple sont négatives ou nulles
        if urtuple[0]<=0 or urtuple[1]<=0:
            
            #Si les conditions sont vérifiées, le message suivant est affiché et la boucle while reprend
            print("Veuillez entrer des valeurs positives et non nulles")
            continue
        
        #Création de deux matrices numpy en utilisant la fonction définie plus haut
        first_arr = user_arr6(urtuple)
        second_arr = user_arr6(urtuple)

        #Création de la variable X contenant le resultat de la méthode cov() calculant la matrice covariante entre les deux matrices créées
        X = np.cov(first_arr,second_arr)

        #Affichage des deux matrices de base et de la matrice covariante. La boucle while est ensuite arretée
        print("Original array1: \n", first_arr ,"\n Original array2: \n", second_arr, "\n Covariance matrix of the said arrays: \n", X)
        break
    
    #Au cas ou l'utilisateur n'entre pas de chiffres, le systèmes renverrai une exception. Elle est captée et le message suivant est affiché à la place
    except ValueError:
        print("Veuillez entrer des chiffres")

entrez nombre de colonnes : 3
nbre de lignes : l
Veuillez entrer des chiffres
entrez nombre de colonnes : 
Veuillez entrer des chiffres
entrez nombre de colonnes : 3
nbre de lignes : 2
Creation d'une matrice

 Ligne 1 :
Entrez la valeur pour la colonne 1 : 1
Entrez la valeur pour la colonne 2 : 2

 Ligne 2 :
Entrez la valeur pour la colonne 1 : 3
Entrez la valeur pour la colonne 2 : 4

 Ligne 3 :
Entrez la valeur pour la colonne 1 : 5
Entrez la valeur pour la colonne 2 : 6
Creation d'une matrice

 Ligne 1 :
Entrez la valeur pour la colonne 1 : 1
Entrez la valeur pour la colonne 2 : 2

 Ligne 2 :
Entrez la valeur pour la colonne 1 : 8
Entrez la valeur pour la colonne 2 : 9

 Ligne 3 :
Entrez la valeur pour la colonne 1 : 3
Entrez la valeur pour la colonne 2 : 4
Original array1: 
 [[1 2]
 [3 4]
 [5 6]] 
 Original array2: 
 [[1 2]
 [8 9]
 [3 4]] 
 Covariance matrix of the said arrays: 
 [[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 

In [13]:
#######   EXERCICE 7   

#Importation du package math pour utiliser des opérations mathématiques complexes
import math

#Déclaration et affectation des constantes C et H
C = 50
H = 30

#Utilisation d'une boucle while infinie pour recommencer le programme
while True:
    
    #Utilisation d'un bloc try ... except pour renvoyer un message spécifique au lieu d'une exception si l'entrée utilisateur est vide, ou un chiffre negatif, ou different d'un chiffre 
    try:
        
        #Déclaration de la variable devant contenir l'entrée de l'utilisateur
        D = input("Entrez des valeurs entieres positives ou nulles separees de virgules: ")

        '''Déclaration de la liste. 
            L'entrée de l'utilisateur sera découpée en plusieurs entiers avec la fonction split(), avec comme séparateur ','.
            Les entiers obtenus sont insérés dans la liste avec la fonction map
        '''
        D_liste = list(map(int, D.split(',')))
        
        #Déclaration d'une liste vide devant contenir les résultats des opérations sur les entiers entrés
        Q_liste = []

        #Utilisation d'une boucle for avec une variable D parcourant la liste
        for D in D_liste:
    
            #Ajout du résultat de l'opération dans la liste prévue, en arrondissant ledit résultat, puis le convertissant en chaine de caracteres
            Q_liste.append(str(round(math.sqrt((2 * C * D) / H))))
        
        #Création d'une variable 'sep' contenant le caractère ','
        sep = ","
        
        #Création d'une variable Q contenant le regroupement des élèments de la liste Q_liste en une chaine de caracteres, en utilisant la fonction join() avec comme séparateur le contenu de la variable 'sep'
        Q = sep.join(Q_liste)
        
        #Affichage des résultats en une chaine de caractères similaire à l'entrée, et arret de la boucle while
        print(Q)
        break
    except ValueError:
        print("Format non pris en charge. Veuillez réessayer.")

Entrez des valeurs entieres positives ou nulles separees de virgules: 
Format non pris en charge. Veuillez réessayer.
Entrez des valeurs entieres positives ou nulles separees de virgules: dhd
Format non pris en charge. Veuillez réessayer.
Entrez des valeurs entieres positives ou nulles separees de virgules: 5;6
Format non pris en charge. Veuillez réessayer.
Entrez des valeurs entieres positives ou nulles separees de virgules: 100,150,-5,0
Format non pris en charge. Veuillez réessayer.
Entrez des valeurs entieres positives ou nulles separees de virgules: 100,150,180
18,22,24
